### ISSUE TITLE
"awsudo" is already the name of another program

### ISSUE THREAD

**Issue by bitglue** [electronicarts/awsudo#3]
There's already a program named "awsudo": https://github.com/paperg/awsudo

If the git histories are any indication, that awsudo predates this one by about five months. The problems with having two programs named exactly the same thing should be obvious, so I'd appreciate it if you could find a unique name for this project.

**Comment by mkwygant** [comment]
Hello, we did see that there were other projects with the same name once we decided to release our code and finally got through the legal process at EA. We have that issue across many of the software projects that we create internally.  We would be very happy to include your project into ours if you would like to issue a pull request to do so.  Both of these scripts are solving similar problems, but with different authentication needs (Federated vs IAM).  Sadly, this will not stop any future projects with the same name.

**Comment by bitglue** [comment]
I'd be happy to accept a PR from you too. Maybe you could rewrite your implementation in Python.
